### ISSUE TITLE
Exclude folders

### ISSUE THREAD

**Issue by jdbancal** [EPFL-ENAC/ENACrestic#3]
Thanks for the great work! Seems to work pretty seamlessly! One question: is it possible to exclude some folders by editing a file like `~/.enacrestic/bkp_exclude` for instance? As an example, one may want to include `/home/user` but exclude `/home/user/.local/Trash`. Is this possible?

**Comment by sbancal** [comment]
Hey,
Thanks for your feedback and the request 😃 .
This is indeed an important feature and has been added to the functionalities.
The new release "0.1.7" is now available.

Here is the dedicated documentation chapter : https://github.com/EPFL-ENAC/ENACrestic#edit-enacresticbkp_exclude-file-optional

Cheers 👋🏼

**Comment by jdbancal** [comment]
Awesome! Thanks!
